# Generated by Django 4.1 on 2023-11-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="census",
            name="locality",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="census",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
