# Generated by Django 4.1 on 2023-11-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0002_census_locality_census_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="census",
            name="has_voted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="census",
            name="vote_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="census",
            name="vote_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IN_PERSON", "In Person"),
                    ("MAIL_IN", "Mail-In"),
                    ("ONLINE", "Online"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="census",
            name="vote_result",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
