# Generated by Django 4.1 on 2023-11-18 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "census",
            "0003_census_has_voted_census_vote_date_census_vote_method_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="census",
            name="has_voted",
        ),
        migrations.RemoveField(
            model_name="census",
            name="locality",
        ),
        migrations.RemoveField(
            model_name="census",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="census",
            name="vote_date",
        ),
        migrations.RemoveField(
            model_name="census",
            name="vote_method",
        ),
        migrations.RemoveField(
            model_name="census",
            name="vote_result",
        ),
        migrations.AddField(
            model_name="census",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="census",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="census",
            name="status",
            field=models.CharField(default="Activo", max_length=20),
        ),
        migrations.AddField(
            model_name="census",
            name="total_voters",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
