# Generated by Django 4.1 on 2023-11-18 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0004_remove_census_has_voted_remove_census_locality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="census",
            name="status",
        ),
        migrations.RemoveField(
            model_name="census",
            name="total_voters",
        ),
    ]
